# Generated by Django 5.1.3 on 2025-11-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_domaine_typecompetence_groupecompetence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='groupe',
        ),
        migrations.AddField(
            model_name='competence',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='Core.domaine'),
        ),
        migrations.DeleteModel(
            name='GroupeCompetence',
        ),
    ]
