# Generated by Django 5.1.3 on 2025-11-24 16:52

from django.db import migrations, models
from Core.models import Personnage


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_add_types_and_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnage',
            name='Niveau',
            field=models.CharField(choices=[('Soldat', 'Soldat'), ('Chef', 'Chef'), ('Commandant', 'Commandant')], default='Soldat', max_length=20),
        ),
    ]
