# Generated by Django 5.1.3 on 2025-11-24 17:38

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_auto_20251124_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnage',
            name='equipe',
            field=models.ForeignKey(
                to='Core.EquipesClass',
                on_delete=models.CASCADE,
                null=True,
                blank=True,
            ),
        ),
    ]