# Generated by Django 5.1.3 on 2025-11-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_auto_20251124_1738'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='competence',
        #     name='competences_mere',
        # ),
        migrations.AddField(
            model_name='competence',
            name='competences_meres',
            field=models.ManyToManyField(blank=True, related_name='competences_filles', to='Core.competence'),
        ),
    ]
