from django.db import migrations


def set_competences_meres(apps, schema_editor):
    Competence = apps.get_model('Core', 'Competence')
    Domaine = apps.get_model('Core', 'Domaine')
    tranchante = Domaine.objects.get(nom="Armes tranchantes")
    contondante = Domaine.objects.get(nom="Armes contondantes")

    # Récupération des compétences existantes
    ## ADRESSE ##
    vol = Competence.objects.get(nom="Vol")
    sabotage_1 = Competence.objects.get(nom="Sabotage 1")
    sabotage_2 = Competence.objects.get(nom="Sabotage 2")
    pickpocket = Competence.objects.get(nom="Pickpocket")
    voleur_habile = Competence.objects.get(nom="Voleur habile")
    professionnel = Competence.objects.get(nom="Professionnel")
    connaissances_coffres_1 = Competence.objects.get(nom="Connaissances des coffres 1")
    connaissances_coffres_2 = Competence.objects.get(nom="Connaissances des coffres 2")
    connaissances_coffres_3 = Competence.objects.get(nom="Connaissances des coffres 3")
    poche_cachée_1 = Competence.objects.get(nom="Poche cachée 1")
    poche_cachée_2 = Competence.objects.get(nom="Poche cachée 2")
    involable = Competence.objects.get(nom="Involable")
    connaissance_de_la_douleur = Competence.objects.get(nom="Connaissance de la douleur")
    rapide_et_brutal = Competence.objects.get(nom="Rapide et brutal")
    expert_des_coups = Competence.objects.get(nom="Expert des coups")
    lent_et_efficace = Competence.objects.get(nom="Lent et efficace")
    expert_des_lames = Competence.objects.get(nom="Expert des lames")
    egorgement = Competence.objects.get(nom="Egorgement")
    assommement = Competence.objects.get(nom="Assommement")
    assassinat = Competence.objects.get(nom="Assassinat")
    surineur = Competence.objects.get(nom="Surineur")
    puissant_1 = Competence.objects.get(nom="Puissant 1")
    puissant_2 = Competence.objects.get(nom="Puissant 2")
    puissant_3 = Competence.objects.get(nom="Puissant 3")
    piege_simple = Competence.objects.get(nom="Piège simple")
    piege_a_effet = Competence.objects.get(nom="Piège à effet")
    piege_desctructeur = Competence.objects.get(nom="Piège destructeur")

    ## MARTIAL ##
    epee_courte = Competence.objects.get(nom="Épée et masse courte (Offert)")
    epee_longue = Competence.objects.get(nom="Épée longue")
    Armes_d_hast_T = Competence.objects.get(nom="Armes d’hast", domaine=tranchante)
    Armes_d_hast_C = Competence.objects.get(nom="Armes d’hast", domaine=contondante)
    Balayage_T = Competence.objects.get(nom="Balayage", domaine=tranchante)
    Balayage_C = Competence.objects.get(nom="Balayage", domaine=contondante)
    two_mains_T = Competence.objects.get(nom="2 Mains", domaine=tranchante)
    two_mains_C = Competence.objects.get(nom="2 Mains", domaine=contondante)
    tranchant = Competence.objects.get(nom="Tranchant")
    ambidextrie_1_T = Competence.objects.get(nom="Ambidextrie 1", domaine=tranchante)
    epee_longue = Competence.objects.get(nom="Épée longue")
    ambidextrie_2_T = Competence.objects.get(nom="Ambidextrie 2", domaine=tranchante)
    masse_courte = Competence.objects.get(nom="Masse courte (Offert)")
    masse_longue = Competence.objects.get(nom="Masse longue")
    ambidextrie_1_C = Competence.objects.get(nom="Ambidextrie 1", domaine=contondante)
    ambidextrie_2_C = Competence.objects.get(nom="Ambidextrie 2", domaine=contondante)
    brisant = Competence.objects.get(nom="Brisant")
    arme_de_jet_1 = Competence.objects.get(nom="Arme de Jet 1")
    arme_de_jet_2 = Competence.objects.get(nom="Arme de Jet 2")
    arme_creuse = Competence.objects.get(nom="Arme creuse")
    arc_et_arbalete = Competence.objects.get(nom="Arc et Arbalète")
    munitions = Competence.objects.get(nom="Munitions")
    armure_legere = Competence.objects.get(nom="Armure légère")
    armure_intermédiaire = Competence.objects.get(nom="Armure intermédiaire")
    armure_lourde = Competence.objects.get(nom="Armure lourde")
    amelioration = Competence.objects.get(nom="Amélioration")
    targe = Competence.objects.get(nom="Targe")
    ecu_et_rondache = Competence.objects.get(nom="Écu et rondache")
    pavois = Competence.objects.get(nom="Pavois")
    resistance = Competence.objects.get(nom="Résistance")

    ## ARTISANAT ##
    bricoleur = Competence.objects.get(nom="Bricoleur")
    achihtecture = Competence.objects.get(nom="Architecture")
    plan_avances = Competence.objects.get(nom="Plans avancés")
    reparation_et_demantelage = Competence.objects.get(nom="Réparation et démantèlement")
    creation = Competence.objects.get(nom="Création")
    expert = Competence.objects.get(nom="Expert")
    apothicaire = Competence.objects.get(nom="Apothicaire")
    potions = Competence.objects.get(nom="Potions")
    elexirs = Competence.objects.get(nom="Élixirs")
    secret_des_potions = Competence.objects.get(nom="Secret des potions")
    poisons = Competence.objects.get(nom="Poisons")
    recettes_secretes = Competence.objects.get(nom="Recettes secrètes")
    secret_des_poisons = Competence.objects.get(nom="Secret des poisons")
    forge_legere = Competence.objects.get(nom="Forge légère")
    forge_intermediaire = Competence.objects.get(nom="Forge intermédiaire")
    forge_lourde = Competence.objects.get(nom="Forge lourde")
    creation_exceptionnelle = Competence.objects.get(nom="Création exceptionnelle")
    cueillette = Competence.objects.get(nom="Cueillette")
    expert_en_plantes = Competence.objects.get(nom="Expert en plantes")
    mineraux = Competence.objects.get(nom="Minerais")
    expert_en_mineraux = Competence.objects.get(nom="Expert en minerais")
    recolte_efficace = Competence.objects.get(nom="Récolte efficace")
    premier_soin = Competence.objects.get(nom="Premier soin")
    stabiliser = Competence.objects.get(nom="Stabiliser")
    soin_d_urgence = Competence.objects.get(nom="Soin d’urgence")
    epideiologie = Competence.objects.get(nom="Épidémiologie")
    chirurgie = Competence.objects.get(nom="Chirurgie")
    greffe = Competence.objects.get(nom="Greffe")

    ## CORPS ET ESPRIT ##
    missive = Competence.objects.get(nom="Missive (offert)")
    cartographe = Competence.objects.get(nom="Cartographe")
    bestiaire = Competence.objects.get(nom="Bestiaire")
    mythes_et_legendes = Competence.objects.get(nom="Mythes et légendes")
    paleographie_1 = Competence.objects.get(nom="Paléographie 1")
    paleographie_2 = Competence.objects.get(nom="Paléographie 2")
    juridique = Competence.objects.get(nom="Juridique")
    administratif = Competence.objects.get(nom="Administratif")
    Robuste = Competence.objects.get(nom="Robuste")
    haute_vitalite = Competence.objects.get(nom="Haute vitalité")
    force_de_la_nature = Competence.objects.get(nom="Force de la nature")
    dur_a_cuire = Competence.objects.get(nom="Dur à cuire")
    esprit_solide = Competence.objects.get(nom="Esprit solide")
    resistance_a_la_douleur = Competence.objects.get(nom="Résistance à la douleur")
    force_mentale = Competence.objects.get(nom="Force mentale")
    exprit_implacable = Competence.objects.get(nom="Esprit implacable")
    apaisement = Competence.objects.get(nom="Apaisement")
    therapie_de_groupe = Competence.objects.get(nom="Thérapie de groupe")
    attenuation_de_folie = Competence.objects.get(nom="Atténuation de folie")
    restructuration_de_l_esprit = Competence.objects.get(nom="Restructuration de l’esprit")
    acceptation = Competence.objects.get(nom="Acceptation")
    voir_l_invisible = Competence.objects.get(nom="Voir l’invisible")
    fluctuation = Competence.objects.get(nom="Fluctuation")
    resistance_aux_flux = Competence.objects.get(nom="Résistance aux flux")
    deceler_l_inconnu = Competence.objects.get(nom="Déceler l’inconnu")

    ## YPERITE ##
    stim = Competence.objects.get(nom="Stim")
    inhalation_d_oxygene_pur = Competence.objects.get(nom="Inhalation d’oxygène pur")
    transfusion = Competence.objects.get(nom="Transfusion")
    la_leeroulette = Competence.objects.get(nom="La Leerolette")
    greffe_de_filtre_a_air = Competence.objects.get(nom="Greffe de filtre à air")
    greffe_d_organes_performants = Competence.objects.get(nom="Greffe d’organes performants")
    nerf_endormi = Competence.objects.get(nom="Nerf endormi")
    coeur_temporaire = Competence.objects.get(nom="Cœur temporaire")
    fusil_magnetique = Competence.objects.get(nom="Fusil magnétique")
    fabrication_de_munitions_magnetique = Competence.objects.get(nom="Fabrication de munitions magnétique")
    defense_magnetique = Competence.objects.get(nom="Défense magnétique")
    champs_magnetique = Competence.objects.get(nom="Champs magnétique")
    specialiste_du_rationnement = Competence.objects.get(nom="Spécialiste du rationnement")
    drone_adaptatif = Competence.objects.get(nom="Drone adaptatif")
    technologie_de_la_cite_volante = Competence.objects.get(nom="Technologie de la cité volante")
    avant_poste_volant = Competence.objects.get(nom="Avant poste volant")
    explorer_sans_crever = Competence.objects.get(nom="Explorer sans crever")
    tactique_furtive = Competence.objects.get(nom="Tactique furtive")
    mine_de_magnetique = Competence.objects.get(nom="Mine de magnétique")
    defense_magnetique = Competence.objects.get(nom="Défense magnétique")
    # Mise à jour des relations "competences_meres ADRESSE"
    sabotage_1.competences_meres.add(vol)
    sabotage_2.competences_meres.add(sabotage_1)
    pickpocket.competences_meres.add(vol)
    voleur_habile.competences_meres.add(pickpocket)
    professionnel.competences_meres.add(voleur_habile)
    connaissances_coffres_2.competences_meres.add(connaissances_coffres_1)
    connaissances_coffres_3.competences_meres.add(connaissances_coffres_2)

    poche_cachée_2.competences_meres.add(poche_cachée_1)
    involable.competences_meres.add(poche_cachée_2)

    rapide_et_brutal.competences_meres.add(connaissance_de_la_douleur)
    expert_des_coups.competences_meres.add(rapide_et_brutal)
    lent_et_efficace.competences_meres.add(connaissance_de_la_douleur)
    expert_des_lames.competences_meres.add(lent_et_efficace)

    assommement.competences_meres.add(egorgement)
    assassinat.competences_meres.add(assommement)
    surineur.competences_meres.add(assassinat)

    puissant_2.competences_meres.add(puissant_1)
    puissant_3.competences_meres.add(puissant_2)

    piege_a_effet.competences_meres.add( piege_simple)
    piege_desctructeur.competences_meres.add(piege_a_effet)


    epee_courte.name = "Épée courte (Offert)"
    epee_courte.save()

    # Mise à jour des relations "competences_meres MARTIAL"
    ambidextrie_1_T.competences_meres.add(epee_courte)
    epee_longue.competences_meres.add(epee_courte)
    ambidextrie_2_T.competences_meres.add(epee_longue, ambidextrie_1_T)
    Armes_d_hast_T.competences_meres.add(epee_longue)
    two_mains_T.competences_meres.add(epee_longue)
    Balayage_T.competences_meres.add(Armes_d_hast_T)
    tranchant.competences_meres.add(two_mains_T)
    ambidextrie_1_C.competences_meres.add(masse_courte)
    masse_longue.competences_meres.add(masse_courte)
    ambidextrie_2_C.competences_meres.add(masse_longue, ambidextrie_1_C)
    Armes_d_hast_C.competences_meres.add(masse_longue)
    two_mains_C.competences_meres.add(masse_longue)
    Balayage_C.competences_meres.add(Armes_d_hast_C)
    brisant.competences_meres.add(two_mains_C)
    arme_de_jet_2.competences_meres.add(arme_de_jet_1)
    arme_creuse.competences_meres.add(arme_de_jet_2)
    arc_et_arbalete.competences_meres.add(arme_de_jet_1)
    munitions.competences_meres.add(arc_et_arbalete)
    armure_intermédiaire.competences_meres.add(armure_legere)
    armure_lourde.competences_meres.add(armure_intermédiaire)
    amelioration.competences_meres.add(armure_lourde)
    ecu_et_rondache.competences_meres.add(targe)
    pavois.competences_meres.add(ecu_et_rondache)
    resistance.competences_meres.add(armure_lourde)

    # Mise à jour des relations "competences_meres ARTISANAT"
    achihtecture.competences_meres.add(bricoleur)
    plan_avances.competences_meres.add(achihtecture)
    reparation_et_demantelage.competences_meres.add(bricoleur)
    creation.competences_meres.add(reparation_et_demantelage)
    expert.competences_meres.add(creation)
    potions.competences_meres.add(apothicaire)
    elexirs.competences_meres.add(potions)
    secret_des_potions.competences_meres.add(elexirs)
    poisons.competences_meres.add(apothicaire)
    recettes_secretes.competences_meres.add(poisons)
    secret_des_poisons.competences_meres.add(recettes_secretes)
    forge_intermediaire.competences_meres.add(forge_legere)
    forge_lourde.competences_meres.add(forge_intermediaire)
    creation_exceptionnelle.competences_meres.add(forge_lourde)
    expert_en_plantes.competences_meres.add(cueillette)
    expert_en_mineraux.competences_meres.add(mineraux)
    recolte_efficace.competences_meres.add(expert_en_plantes, expert_en_mineraux)
    stabiliser.competences_meres.add(premier_soin)
    soin_d_urgence.competences_meres.add(stabiliser)
    epideiologie.competences_meres.add(premier_soin)
    chirurgie.competences_meres.add(epideiologie)
    greffe.competences_meres.add(chirurgie)

    # Mise à jour des relations "competences_meres CORPS ET ESPRIT"
    cartographe.competences_meres.add(missive)
    bestiaire.competences_meres.add(cartographe)
    mythes_et_legendes.competences_meres.add(bestiaire)
    paleographie_1.competences_meres.add(missive)
    paleographie_2.competences_meres.add(paleographie_1)
    juridique.competences_meres.add(missive)
    administratif.competences_meres.add(juridique)
    haute_vitalite.competences_meres.add(Robuste)
    force_de_la_nature.competences_meres.add(haute_vitalite)
    dur_a_cuire.competences_meres.add(force_de_la_nature)
    resistance_a_la_douleur.competences_meres.add(esprit_solide)
    force_mentale.competences_meres.add(resistance_a_la_douleur)
    exprit_implacable.competences_meres.add(force_mentale)
    therapie_de_groupe.competences_meres.add(apaisement)
    restructuration_de_l_esprit.competences_meres.add(apaisement)
    attenuation_de_folie.competences_meres.add(therapie_de_groupe, restructuration_de_l_esprit)
    acceptation.competences_meres.add(attenuation_de_folie, restructuration_de_l_esprit)
    fluctuation.competences_meres.add(voir_l_invisible)
    resistance_aux_flux.competences_meres.add(fluctuation)
    deceler_l_inconnu.competences_meres.add(resistance_aux_flux)

    # Mise à jour des relations "competences_meres YPERITE"
    inhalation_d_oxygene_pur.competences_meres.add(stim)
    transfusion.competences_meres.add(inhalation_d_oxygene_pur)
    la_leeroulette.competences_meres.add(transfusion)
    greffe_d_organes_performants.competences_meres.add(greffe_de_filtre_a_air)
    nerf_endormi.competences_meres.add(greffe_d_organes_performants)
    coeur_temporaire.competences_meres.add(nerf_endormi)
    fabrication_de_munitions_magnetique.competences_meres.add(fusil_magnetique)
    defense_magnetique.competences_meres.add(fabrication_de_munitions_magnetique)
    champs_magnetique.competences_meres.add(defense_magnetique)
    drone_adaptatif.competences_meres.add(specialiste_du_rationnement)
    technologie_de_la_cite_volante.competences_meres.add(drone_adaptatif)
    avant_poste_volant.competences_meres.add(technologie_de_la_cite_volante)
    tactique_furtive.competences_meres.add(explorer_sans_crever)
    mine_de_magnetique.competences_meres.add(tactique_furtive)
    defense_magnetique.competences_meres.add(mine_de_magnetique)



class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0009_remove_competence_competence_mere_and_more'),  # Remplace par la dernière migration de ton app
    ]

    operations = [
        migrations.RunPython(set_competences_meres),
    ]