# Generated by Django 5.1.3 on 2025-11-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_add_competence_mere'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='double',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
