# Generated by Django 5.1.3 on 2025-12-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_personnage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='offer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
