# Generated by Django 5.1.3 on 2025-12-11 12:16

from django.db import migrations, models


def setCompOffer(apps, schema_editor):
    Competence = apps.get_model('Core', 'Competence')
    missive = Competence.objects.get(pk=85)
    masse = Competence.objects.get(pk=38)
    epee = Competence.objects.get(pk=29)
    missive.offer = True
    missive.save()
    masse.offer = True
    masse.save()
    epee.offer = True
    epee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_competence_offer'),
    ]

    operations = [
       migrations.RunPython(setCompOffer),
    ]
