# Generated by Django 5.1.3 on 2025-12-11 12:16

from django.db import migrations, models


def setCompOffer(apps, schema_editor):
    Competence = apps.get_model('Core', 'Competence')
    epee_courte = Competence.objects.get(pk=28)
    epee = Competence.objects.get(pk=29)
    epee_courte.offer = True
    epee_courte.save()
    epee.offer = False
    epee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_competence_offer_add'),
    ]

    operations = [
       migrations.RunPython(setCompOffer),
    ]
